"""Non-secret trading configuration.
Secrets belong in environment variables, not this file.
"""

# Exchange / runtime
EXCHANGE_ID = "binance"
EXECUTION_TIMEFRAME = "1m"
PAPER_TRADE = True
STARTING_CAPITAL = 1000.0
FETCH_TIMEOUT_MS = 20000
INTRA_CANDLE_SECONDS = 5

# Universe
QUOTE_CURRENCY = "USDT"
FAVOURITE_TOKENS = ""  # Example: "ZEC/USDT, LINK/USDT". When set, market scanning is skipped.
MIN_VOLUME_USDT = 1_000_000
TOP_CANDIDATE_COUNT = 10
SYMBOL_SCAN_INTERVAL_SECONDS = 60
LARGE_CAP_BLACKLIST = {"BTC", "ETH", "SOL", "XRP", "BNB"}

# Trading model
WINDOW_SIZE = 250
DONCHIAN_ENTRY_PERIOD = 20
DONCHIAN_EXIT_PERIOD = 10
EMA_FAST_PERIOD = 20
EMA_SLOW_PERIOD = 50
ATR_PERIOD = 14
ADX_PERIOD = 14
MIN_ADX = 20.0
STRONG_ADX = 30.0
EXTREME_ADX = 40.0
MIN_TREND_PCT = 0.002
MAX_ATR_PCT = 0.08
MIN_ATR_PCT = 0.0005
MIN_VOLUME_RATIO = 1.0
BREAKOUT_BUFFER_ATR = 0.10
MIN_TREND_AGE = 2

# Entry quality / regime gating
REQUIRE_VOLUME_CONFIRMATION = True
REQUIRE_EMA_ALIGNMENT = True
REQUIRE_ADX_CONFIRMATION = True
ALLOW_LONG = True
ALLOW_SHORT = True
REQUIRE_DIRECTIONAL_CANDLE = True
MIN_DIRECTIONAL_CANDLE_BODY_PCT = 0.0005
MIN_ENTRY_CONFIDENCE = 0.30
SHORT_EXTRA_VOLUME_RATIO = 1.10
SHORT_EXTRA_ADX = 22.0
MIN_PRICE_TREND_PCT_FOR_ENTRY = 0.0025

# Risk / position sizing
RISK_PER_TRADE_PCT = 0.01
MAX_MARGIN_PCT = 0.30
MIN_STOP_PCT = 0.005
MAX_STOP_PCT = 0.04
STOP_ATR_MULTIPLIER = 1.75
STOP_SWING_LOOKBACK = 10
STOP_SWING_BUFFER_ATR = 0.20
REINVEST_PROFITS = True
TAKER_FEE_PCT = 0.001

# Leverage: deliberately low; only increase when trend regime is objectively strong.
BASE_LEVERAGE = 1.0
STRONG_TREND_LEVERAGE = 2.0
EXTREME_TREND_LEVERAGE = 3.0
MAX_LEVERAGE = 3.0

# Exit / trailing
TRAIL_ACTIVATION_R = 1.0
TRAIL_ATR_MULTIPLIER = 2.0
TRAIL_MIN_DISTANCE_PCT = 0.003
TRAIL_MAX_DISTANCE_PCT = 0.018
REVERSAL_CONFIRMATION_CANDLES = 2
EXIT_ON_OPPOSITE_BREAKOUT = True
EXIT_ON_EMA_REVERSAL = True

# Logging
LOG_DIRECTORY = "logs"
TRADE_LOG_FILENAME = "trades.csv"

# Email configuration is intentionally secret-free.
ENABLE_EMAIL = True
EMAIL_COOLDOWN_SECONDS = 3600
